
BEGIN;
-- CreateEnum
CREATE TYPE "PriceType" AS ENUM ('FIXED', 'STARTING_FROM', 'POA');

-- CreateEnum
CREATE TYPE "BillingType" AS ENUM ('ONE_TIME', 'MONTHLY');

-- AlterTable
ALTER TABLE "packages" ADD COLUMN     "bestFor" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "billingType" "BillingType" NOT NULL DEFAULT 'ONE_TIME',
ADD COLUMN     "features" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "isPublished" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "priceType" "PriceType" NOT NULL DEFAULT 'POA',
ADD COLUMN     "purchasable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "serviceId" TEXT,
ADD COLUMN     "shortDescription" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tier" TEXT NOT NULL DEFAULT 'Starter',
ADD COLUMN     "updatedById" TEXT,
ALTER COLUMN "amount" DROP NOT NULL;

-- CreateTable
CREATE TABLE "services" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "heroTitle" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "bodyHeading" TEXT NOT NULL DEFAULT '',
    "bodyText" TEXT NOT NULL DEFAULT '',
    "sections" JSONB NOT NULL DEFAULT '[]',
    "iconKey" TEXT NOT NULL DEFAULT 'code',
    "seoTitle" TEXT NOT NULL DEFAULT '',
    "seoDescription" TEXT NOT NULL DEFAULT '',
    "showOnHomepage" BOOLEAN NOT NULL DEFAULT false,
    "showInFooter" BOOLEAN NOT NULL DEFAULT false,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" TEXT,
    "updatedById" TEXT,

    CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_aliases" (
    "slug" TEXT NOT NULL,
    "serviceId" TEXT NOT NULL,

    CONSTRAINT "service_aliases_pkey" PRIMARY KEY ("slug")
);

-- CreateTable
CREATE TABLE "bundles" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "isSignature" BOOLEAN NOT NULL DEFAULT false,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedById" TEXT,

    CONSTRAINT "bundles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bundle_components" (
    "bundleId" TEXT NOT NULL,
    "packageId" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "bundle_components_pkey" PRIMARY KEY ("bundleId","packageId")
);

-- CreateIndex
CREATE UNIQUE INDEX "services_slug_key" ON "services"("slug");

-- CreateIndex
CREATE INDEX "services_isPublished_sortOrder_idx" ON "services"("isPublished", "sortOrder");

-- CreateIndex
CREATE UNIQUE INDEX "bundles_slug_key" ON "bundles"("slug");

-- CreateIndex
CREATE INDEX "bundles_isPublished_sortOrder_idx" ON "bundles"("isPublished", "sortOrder");

-- CreateIndex
CREATE INDEX "packages_serviceId_isPublished_sortOrder_idx" ON "packages"("serviceId", "isPublished", "sortOrder");

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "services" ADD CONSTRAINT "services_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "services" ADD CONSTRAINT "services_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_aliases" ADD CONSTRAINT "service_aliases_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bundles" ADD CONSTRAINT "bundles_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bundle_components" ADD CONSTRAINT "bundle_components_bundleId_fkey" FOREIGN KEY ("bundleId") REFERENCES "bundles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bundle_components" ADD CONSTRAINT "bundle_components_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Backfill original catalogue once. Preserve existing package IDs, names, prices and orders.
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-website-design-development', 'website-design-development', 'Website Development', 'A professional, secure online presence — from a simple starter site to a full digital platform.', 'Website Development', 'A professional, secure online presence — from a simple starter site to a full digital platform.', 'Elevate Your Digital Presence', 'In today''s fast-paced digital landscape, an off-the-shelf solution simply doesn''t cut it. We engineer custom web platforms tailored explicitly to your operational workflows and customer journeys.', '[{"title":"Custom Web Applications","description":"Tailor-made web apps built with modern frameworks focused on scalability."},{"title":"E-Commerce Solutions","description":"Robust platforms to drive your online sales with high performance."},{"title":"Performance Optimization","description":"Auditing and upgrading your platform to achieve blazing fast load times."},{"title":"Ongoing Maintenance","description":"Constant monitoring, updating, and feature deployment without downtime."}]'::jsonb, 'code', 'Website Development Services', 'A professional, secure online presence — from a simple starter site to a full digital platform.', true, true, true, 1, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-branding-identity', 'branding-identity', 'Branding & Design', 'A cohesive, professional look that builds trust and sets you apart from competitors.', 'Branding & Design', 'A cohesive, professional look that builds trust and sets you apart from competitors.', 'What we offer', '', '[]'::jsonb, 'paintbrush', 'Branding & Design Services', 'A cohesive, professional look that builds trust and sets you apart from competitors.', true, true, true, 6, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-graphic-design-for-business', 'graphic-design-for-business', 'Graphic Design for Business', 'High-quality design assets that keep your business looking polished every single day.', 'Graphic Design for Business', 'High-quality design assets that keep your business looking polished every single day.', 'What we offer', '', '[]'::jsonb, 'compass', 'Graphic Design for Business Services', 'High-quality design assets that keep your business looking polished every single day.', false, true, true, 8, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-seo', 'seo', 'SEO', 'Strategies that deliver real traffic, leads, and sales — without the vanity metrics.', 'Be easier to find. Turn searches into enquiries.', 'VolTechAI helps businesses improve their organic visibility with technical, on-page and local SEO built around real commercial goals.', 'SEO that supports sustainable growth', 'We start with an audit, prioritise the changes most likely to help, and explain the work in plain English. Whether you need better foundations or ongoing support, we can shape the work around your business.', '[{"title":"Technical SEO","description":"Improve crawlability, site speed, mobile usability, indexing and structured data."},{"title":"On-page SEO","description":"Create clear page titles, headings, internal links and useful content aligned with customer intent."},{"title":"Local SEO","description":"Strengthen your visibility for relevant searches in East Ham, London and the areas you serve."},{"title":"SEO reporting","description":"Track rankings, organic visits and enquiries with straightforward reporting and recommendations."}]'::jsonb, 'search', 'SEO Services in London', 'Strategies that deliver real traffic, leads, and sales — without the vanity metrics.', true, true, true, 4, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-ai-services', 'ai-services', 'AI Services', 'Practical, secure AI tools that actually save time and money, implemented safely.', 'AI Services', 'Practical, secure AI tools that actually save time and money, implemented safely.', 'What we offer', '', '[]'::jsonb, 'bot', 'AI Services Services', 'Practical, secure AI tools that actually save time and money, implemented safely.', true, true, true, 5, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-cybersecurity-services', 'cybersecurity-services', 'Cybersecurity Services', 'Robust protection for your networks, data, and reputation.', 'Cybersecurity Services', 'Robust protection for your networks, data, and reputation.', 'What we offer', '', '[]'::jsonb, 'shield', 'Cybersecurity Services Services', 'Robust protection for your networks, data, and reputation.', true, true, true, 7, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-governance-risk-compliance', 'governance-risk-compliance', 'Governance, Risk & Compliance (GRC)', 'Policies, gap analyses, and evidence to prove you follow the rules and handle data safely.', 'Governance, Risk & Compliance (GRC)', 'Policies, gap analyses, and evidence to prove you follow the rules and handle data safely.', 'What we offer', '', '[]'::jsonb, 'scale', 'Governance, Risk & Compliance (GRC) Services', 'Policies, gap analyses, and evidence to prove you follow the rules and handle data safely.', false, true, true, 9, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-app-development', 'app-development', 'App Development', 'User-friendly mobile and web apps designed around your customers and business workflows.', 'Apps built around the way your business works', 'We design and develop useful mobile and web apps with clear user journeys, reliable integrations and room to grow.', 'From idea to working product', 'We can help with discovery, UX, development, testing and launch for customer-facing apps, internal tools and connected digital products.', '[]'::jsonb, 'monitor', 'App Development Services', 'Custom mobile and web app development from VolTechAI for businesses in London and across the UK.', true, true, true, 2, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "services" ("id", "slug", "name", "summary", "heroTitle", "description", "bodyHeading", "bodyText", "sections", "iconKey", "seoTitle", "seoDescription", "showOnHomepage", "showInFooter", "isPublished", "sortOrder", "updatedAt") VALUES ('service-software-development', 'software-development', 'Software Development', 'Bespoke platforms, automation and integrations that make complex business processes simpler.', 'Software that solves the problem behind the brief', 'VolTechAI creates dependable business software, automation and integrations that reduce friction and support better decisions.', 'Practical, maintainable technology', 'We turn operational challenges into clear technical plans, then build and refine software with security, performance and long-term support in mind.', '[]'::jsonb, 'code', 'Software Development Services', 'Bespoke software development from VolTechAI for organisations in London and across the UK.', true, true, true, 3, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-website-get-online', 'website-get-online', 'Get Online', 45000, 'gbp', 'Starter', 'A clean, professional website so customers can find you, learn what you do, and trust you.', ARRAY['1–5 page responsive website','Mobile & tablet friendly design','Contact form & Google Maps integration','Basic on-page SEO setup','1 round of revisions']::text[], 'New businesses and sole traders needing a professional first impression online.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-website-design-development', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'website-get-online', "tier" = 'Starter', "shortDescription" = 'A clean, professional website so customers can find you, learn what you do, and trust you.', "features" = ARRAY['1–5 page responsive website','Mobile & tablet friendly design','Contact form & Google Maps integration','Basic on-page SEO setup','1 round of revisions']::text[], "bestFor" = 'New businesses and sole traders needing a professional first impression online.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-website-design-development' WHERE "slug" = 'website-get-online' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-website-grow-business', 'website-grow-business', 'Grow Your Business', 120000, 'gbp', 'Growth', 'A larger, custom-designed website built to convert visitors into customers.', ARRAY['6–12 pages, custom designed (not a generic template)','Content Management System (WordPress / Webflow)','Online booking or enquiry forms','On-page SEO across all pages','Google Analytics & Search Console setup','2 rounds of revisions']::text[], 'Small businesses ready to actively market themselves and generate leads online.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-website-design-development', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'website-grow-business', "tier" = 'Growth', "shortDescription" = 'A larger, custom-designed website built to convert visitors into customers.', "features" = ARRAY['6–12 pages, custom designed (not a generic template)','Content Management System (WordPress / Webflow)','Online booking or enquiry forms','On-page SEO across all pages','Google Analytics & Search Console setup','2 rounds of revisions']::text[], "bestFor" = 'Small businesses ready to actively market themselves and generate leads online.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-website-design-development' WHERE "slug" = 'website-grow-business' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-website-full-business-platform', 'website-full-business-platform', 'Full Business Platform', 300000, 'gbp', 'Pro', 'A bespoke, powerful platform that can take payments, manage customers, or run as an online shop.', ARRAY['Fully bespoke design & UX','E-commerce or client portal functionality','Integrations (CRM, payment gateway, booking systems)','Performance & security hardening','Ongoing maintenance retainer available']::text[], 'Established SMEs that need their website to actively run part of the business.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 3, 'service-website-design-development', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'website-full-business-platform', "tier" = 'Pro', "shortDescription" = 'A bespoke, powerful platform that can take payments, manage customers, or run as an online shop.', "features" = ARRAY['Fully bespoke design & UX','E-commerce or client portal functionality','Integrations (CRM, payment gateway, booking systems)','Performance & security hardening','Ongoing maintenance retainer available']::text[], "bestFor" = 'Established SMEs that need their website to actively run part of the business.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-website-design-development' WHERE "slug" = 'website-full-business-platform' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-branding-look-professional', 'branding-look-professional', 'Look Professional', 25000, 'gbp', 'Starter', 'A logo and simple colour/font system so your business looks consistent everywhere.', ARRAY['Custom logo design (2 concepts, 2 revisions)','Colour palette & typography selection','1-page brand summary sheet','Logo files for web & print']::text[], 'New or rebranding businesses that need a professional identity fast.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-branding-identity', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'branding-look-professional', "tier" = 'Starter', "shortDescription" = 'A logo and simple colour/font system so your business looks consistent everywhere.', "features" = ARRAY['Custom logo design (2 concepts, 2 revisions)','Colour palette & typography selection','1-page brand summary sheet','Logo files for web & print']::text[], "bestFor" = 'New or rebranding businesses that need a professional identity fast.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-branding-identity' WHERE "slug" = 'branding-look-professional' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-branding-complete-brand-look', 'branding-complete-brand-look', 'Complete Brand Look', 70000, 'gbp', 'Growth', 'A full identity system so everything you put out — online and in print — looks like you.', ARRAY['Everything in Starter','Business card & letterhead templates','Social media templates (profile, cover, post)','5–10 page brand guidelines document']::text[], 'Growing businesses building a consistent presence across multiple channels.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-branding-identity', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'branding-complete-brand-look', "tier" = 'Growth', "shortDescription" = 'A full identity system so everything you put out — online and in print — looks like you.', "features" = ARRAY['Everything in Starter','Business card & letterhead templates','Social media templates (profile, cover, post)','5–10 page brand guidelines document']::text[], "bestFor" = 'Growing businesses building a consistent presence across multiple channels.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-branding-identity' WHERE "slug" = 'branding-complete-brand-look' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-branding-brand-strategy', 'branding-brand-strategy', 'Brand Strategy', 150000, 'gbp', 'Pro', 'We help define what makes you different, and how to talk about your business to attract the right customers.', ARRAY['Everything in Growth','Positioning & messaging workshop','Competitor analysis','Tone-of-voice guide','Full brand strategy document']::text[], 'Businesses in competitive markets that need clear differentiation.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 3, 'service-branding-identity', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'branding-brand-strategy', "tier" = 'Pro', "shortDescription" = 'We help define what makes you different, and how to talk about your business to attract the right customers.', "features" = ARRAY['Everything in Growth','Positioning & messaging workshop','Competitor analysis','Tone-of-voice guide','Full brand strategy document']::text[], "bestFor" = 'Businesses in competitive markets that need clear differentiation.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-branding-identity' WHERE "slug" = 'branding-brand-strategy' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-graphic-design-everyday-essentials', 'graphic-design-everyday-essentials', 'Everyday Essentials', 20000, 'gbp', 'Starter', 'The core design assets every business needs to look put-together, day to day.', ARRAY['Business card design','Email signature design','5-post social media template set','1 round of revisions']::text[], 'Businesses that have a logo but need everyday materials to match.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-graphic-design-for-business', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'graphic-design-everyday-essentials', "tier" = 'Starter', "shortDescription" = 'The core design assets every business needs to look put-together, day to day.', "features" = ARRAY['Business card design','Email signature design','5-post social media template set','1 round of revisions']::text[], "bestFor" = 'Businesses that have a logo but need everyday materials to match.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-graphic-design-for-business' WHERE "slug" = 'graphic-design-everyday-essentials' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-graphic-design-marketing-collateral', 'graphic-design-marketing-collateral', 'Marketing Collateral', 45000, 'gbp', 'Growth', 'The materials you need to actually promote the business — in print and online.', ARRAY['Flyer or brochure design (up to 6 pages)','Presentation / pitch deck design template','10-post social media template set','Print-ready & digital file formats','2 rounds of revisions']::text[], 'Businesses actively marketing themselves at events, online, or to investors.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-graphic-design-for-business', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'graphic-design-marketing-collateral', "tier" = 'Growth', "shortDescription" = 'The materials you need to actually promote the business — in print and online.', "features" = ARRAY['Flyer or brochure design (up to 6 pages)','Presentation / pitch deck design template','10-post social media template set','Print-ready & digital file formats','2 rounds of revisions']::text[], "bestFor" = 'Businesses actively marketing themselves at events, online, or to investors.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-graphic-design-for-business' WHERE "slug" = 'graphic-design-marketing-collateral' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-graphic-design-full-design-support', 'graphic-design-full-design-support', 'Full Design Support', 40000, 'gbp', 'Pro', 'Ongoing design support so you''re never stuck waiting on a freelancer for the next asset.', ARRAY['Monthly allowance of design requests (social posts, ads, one-pagers)','Presentation & proposal design','Packaging or signage design as needed','Brand consistency oversight across all assets','Priority turnaround']::text[], 'Businesses that produce marketing or client-facing materials regularly.', 'STARTING_FROM', 'MONTHLY', false, true, true, 3, 'service-graphic-design-for-business', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'graphic-design-full-design-support', "tier" = 'Pro', "shortDescription" = 'Ongoing design support so you''re never stuck waiting on a freelancer for the next asset.', "features" = ARRAY['Monthly allowance of design requests (social posts, ads, one-pagers)','Presentation & proposal design','Packaging or signage design as needed','Brand consistency oversight across all assets','Priority turnaround']::text[], "bestFor" = 'Businesses that produce marketing or client-facing materials regularly.', "priceType" = 'STARTING_FROM', "billingType" = 'MONTHLY', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-graphic-design-for-business' WHERE "slug" = 'graphic-design-full-design-support' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-marketing-get-found', 'marketing-get-found', 'Get Found', 30000, 'gbp', 'Starter', 'The essentials to be found on Google Search and Maps by local customers.', ARRAY['Google Business Profile setup & optimisation','Local SEO fundamentals (on-page keywords, meta tags, site structure)','Keyword research (up to 10 target keywords)','Monthly performance summary']::text[], 'Local businesses wanting to be found on Google Search and Maps.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-seo', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'marketing-get-found', "tier" = 'Starter', "shortDescription" = 'The essentials to be found on Google Search and Maps by local customers.', "features" = ARRAY['Google Business Profile setup & optimisation','Local SEO fundamentals (on-page keywords, meta tags, site structure)','Keyword research (up to 10 target keywords)','Monthly performance summary']::text[], "bestFor" = 'Local businesses wanting to be found on Google Search and Maps.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-seo' WHERE "slug" = 'marketing-get-found' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-marketing-grow-your-traffic', 'marketing-grow-your-traffic', 'Grow Your Traffic', 70000, 'gbp', 'Growth', 'Consistent organic growth through ongoing SEO, content and social media activity.', ARRAY['Everything in Starter','Ongoing on-page & technical SEO','Content calendar & blog writing (2 posts/month)','Social media management (2 platforms)','Monthly reporting & strategy call']::text[], 'Businesses ready to build consistent organic traffic and social presence.', 'STARTING_FROM', 'MONTHLY', false, true, true, 2, 'service-seo', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'marketing-grow-your-traffic', "tier" = 'Growth', "shortDescription" = 'Consistent organic growth through ongoing SEO, content and social media activity.', "features" = ARRAY['Everything in Starter','Ongoing on-page & technical SEO','Content calendar & blog writing (2 posts/month)','Social media management (2 platforms)','Monthly reporting & strategy call']::text[], "bestFor" = 'Businesses ready to build consistent organic traffic and social presence.', "priceType" = 'STARTING_FROM', "billingType" = 'MONTHLY', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-seo' WHERE "slug" = 'marketing-grow-your-traffic' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-marketing-full-growth-engine', 'marketing-full-growth-engine', 'Full Growth Engine', 150000, 'gbp', 'Pro', 'A complete customer acquisition engine across paid and organic channels.', ARRAY['Everything in Growth','Paid search & social ad management (Google / Meta)','Conversion rate optimisation','Email marketing campaigns','Quarterly strategy & competitor review']::text[], 'SMEs ready to scale customer acquisition across multiple channels.', 'STARTING_FROM', 'MONTHLY', false, true, true, 3, 'service-seo', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'marketing-full-growth-engine', "tier" = 'Pro', "shortDescription" = 'A complete customer acquisition engine across paid and organic channels.', "features" = ARRAY['Everything in Growth','Paid search & social ad management (Google / Meta)','Conversion rate optimisation','Email marketing campaigns','Quarterly strategy & competitor review']::text[], "bestFor" = 'SMEs ready to scale customer acquisition across multiple channels.', "priceType" = 'STARTING_FROM', "billingType" = 'MONTHLY', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-seo' WHERE "slug" = 'marketing-full-growth-engine' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-ai-readiness-strategy', 'ai-readiness-strategy', 'AI Readiness & Strategy', 40000, 'gbp', 'Starter', 'A clear, prioritised picture of where AI can genuinely save time or cost in your business — before you spend a penny on tools.', ARRAY['AI opportunity assessment across core operations','Tool shortlist matched to business size & budget','Data readiness & risk check','Prioritised adoption roadmap']::text[], 'SMEs curious about AI but unsure where to start or what''s worth the investment.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-ai-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'ai-readiness-strategy', "tier" = 'Starter', "shortDescription" = 'A clear, prioritised picture of where AI can genuinely save time or cost in your business — before you spend a penny on tools.', "features" = ARRAY['AI opportunity assessment across core operations','Tool shortlist matched to business size & budget','Data readiness & risk check','Prioritised adoption roadmap']::text[], "bestFor" = 'SMEs curious about AI but unsure where to start or what''s worth the investment.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-ai-services' WHERE "slug" = 'ai-readiness-strategy' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-ai-powered-automation', 'ai-powered-automation', 'AI-Powered Automation', 90000, 'gbp', 'Growth', 'Hands-on implementation of AI tools into everyday workflows, with staff trained to actually use them.', ARRAY['Everything in Starter','Workflow automation (chatbots, document processing, email/customer service)','Integration with existing tools (CRM, accounting, helpdesk)','Staff training on new AI tools','30-day post-launch support']::text[], 'Businesses ready to put AI to work in day-to-day operations.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-ai-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'ai-powered-automation', "tier" = 'Growth', "shortDescription" = 'Hands-on implementation of AI tools into everyday workflows, with staff trained to actually use them.', "features" = ARRAY['Everything in Starter','Workflow automation (chatbots, document processing, email/customer service)','Integration with existing tools (CRM, accounting, helpdesk)','Staff training on new AI tools','30-day post-launch support']::text[], "bestFor" = 'Businesses ready to put AI to work in day-to-day operations.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-ai-services' WHERE "slug" = 'ai-powered-automation' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-ai-custom-secure-integration', 'ai-custom-secure-integration', 'Custom AI & Secure Integration', 250000, 'gbp', 'Pro', 'A bespoke AI solution, built with security controls from day one rather than bolted on afterwards — VolTechAI''s signature ''secure-by-design'' approach.', ARRAY['Everything in Growth','Bespoke AI solution build (custom chatbot, internal tool, or predictive model)','Security-by-design implementation (access control, data handling, vendor risk checks)','Optional ongoing AI Assurance retainer (monthly monitoring & tool review)','Quarterly AI strategy review']::text[], 'SMEs wanting a genuinely bespoke AI solution, implemented securely and built to scale.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 3, 'service-ai-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'ai-custom-secure-integration', "tier" = 'Pro', "shortDescription" = 'A bespoke AI solution, built with security controls from day one rather than bolted on afterwards — VolTechAI''s signature ''secure-by-design'' approach.', "features" = ARRAY['Everything in Growth','Bespoke AI solution build (custom chatbot, internal tool, or predictive model)','Security-by-design implementation (access control, data handling, vendor risk checks)','Optional ongoing AI Assurance retainer (monthly monitoring & tool review)','Quarterly AI strategy review']::text[], "bestFor" = 'SMEs wanting a genuinely bespoke AI solution, implemented securely and built to scale.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-ai-services' WHERE "slug" = 'ai-custom-secure-integration' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-cybersecurity-health-check', 'cybersecurity-health-check', 'Health Check', 35000, 'gbp', 'Starter', 'We check your systems for weak spots and give you a simple, jargon-free report on what to fix.', ARRAY['External vulnerability scan','Basic security posture review','Plain-English findings report','Prioritised action list']::text[], 'Businesses who''ve never had a security review and want a baseline.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-cybersecurity-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'cybersecurity-health-check', "tier" = 'Starter', "shortDescription" = 'We check your systems for weak spots and give you a simple, jargon-free report on what to fix.', "features" = ARRAY['External vulnerability scan','Basic security posture review','Plain-English findings report','Prioritised action list']::text[], "bestFor" = 'Businesses who''ve never had a security review and want a baseline.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-cybersecurity-services' WHERE "slug" = 'cybersecurity-health-check' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-cybersecurity-stay-protected', 'cybersecurity-stay-protected', 'Stay Protected', 90000, 'gbp', 'Growth', 'We fix the weak spots, train your team to spot scams, and set up strong login security.', ARRAY['Everything in Starter','Guided remediation of findings','Staff phishing & scam-awareness training','Password policy & Multi-Factor Authentication setup','Cyber Essentials readiness guidance']::text[], 'Businesses handling customer data or wanting Cyber Essentials certification.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-cybersecurity-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'cybersecurity-stay-protected', "tier" = 'Growth', "shortDescription" = 'We fix the weak spots, train your team to spot scams, and set up strong login security.', "features" = ARRAY['Everything in Starter','Guided remediation of findings','Staff phishing & scam-awareness training','Password policy & Multi-Factor Authentication setup','Cyber Essentials readiness guidance']::text[], "bestFor" = 'Businesses handling customer data or wanting Cyber Essentials certification.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-cybersecurity-services' WHERE "slug" = 'cybersecurity-stay-protected' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-cybersecurity-ongoing-protection', 'cybersecurity-ongoing-protection', 'Ongoing Protection', 25000, 'gbp', 'Pro', 'We continuously watch over your systems, so issues are caught early — before they become a crisis.', ARRAY['Ongoing monitoring & alerts','Quarterly security reviews','Incident response plan','Recurring staff training programme','Priority support']::text[], 'Businesses that can''t afford downtime or a data breach.', 'STARTING_FROM', 'MONTHLY', false, true, true, 3, 'service-cybersecurity-services', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'cybersecurity-ongoing-protection', "tier" = 'Pro', "shortDescription" = 'We continuously watch over your systems, so issues are caught early — before they become a crisis.', "features" = ARRAY['Ongoing monitoring & alerts','Quarterly security reviews','Incident response plan','Recurring staff training programme','Priority support']::text[], "bestFor" = 'Businesses that can''t afford downtime or a data breach.', "priceType" = 'STARTING_FROM', "billingType" = 'MONTHLY', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-cybersecurity-services' WHERE "slug" = 'cybersecurity-ongoing-protection' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-grc-am-i-compliant', 'grc-am-i-compliant', 'Am I Compliant?', 40000, 'gbp', 'Starter', 'We check whether your business follows the rules it needs to (e.g. UK GDPR) and tell you what''s missing.', ARRAY['Gap analysis against one framework (GDPR / Cyber Essentials)','Plain-English findings summary','Prioritised remediation roadmap']::text[], 'Businesses unsure what compliance actually applies to them.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 1, 'service-governance-risk-compliance', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'grc-am-i-compliant', "tier" = 'Starter', "shortDescription" = 'We check whether your business follows the rules it needs to (e.g. UK GDPR) and tell you what''s missing.', "features" = ARRAY['Gap analysis against one framework (GDPR / Cyber Essentials)','Plain-English findings summary','Prioritised remediation roadmap']::text[], "bestFor" = 'Businesses unsure what compliance actually applies to them.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 1, "serviceId" = 'service-governance-risk-compliance' WHERE "slug" = 'grc-am-i-compliant' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-grc-get-compliant', 'grc-get-compliant', 'Get Compliant', 110000, 'gbp', 'Growth', 'We write the policies your business needs and train your staff, so you''re properly covered.', ARRAY['Everything in Starter','Policy drafting (data protection, acceptable use, incident response)','Staff compliance training','Documented evidence pack']::text[], 'Businesses that need to demonstrate compliance to clients, insurers, or regulators.', 'STARTING_FROM', 'ONE_TIME', false, true, true, 2, 'service-governance-risk-compliance', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'grc-get-compliant', "tier" = 'Growth', "shortDescription" = 'We write the policies your business needs and train your staff, so you''re properly covered.', "features" = ARRAY['Everything in Starter','Policy drafting (data protection, acceptable use, incident response)','Staff compliance training','Documented evidence pack']::text[], "bestFor" = 'Businesses that need to demonstrate compliance to clients, insurers, or regulators.', "priceType" = 'STARTING_FROM', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 2, "serviceId" = 'service-governance-risk-compliance' WHERE "slug" = 'grc-get-compliant' AND "serviceId" IS NULL;
INSERT INTO "packages" ("id", "slug", "name", "amount", "currency", "tier", "shortDescription", "features", "bestFor", "priceType", "billingType", "purchasable", "isPublished", "isActive", "sortOrder", "serviceId", "updatedAt") VALUES ('offer-grc-certification-ready', 'grc-certification-ready', 'Certification Ready', NULL, 'gbp', 'Pro', 'We prepare your business for official certification (e.g. ISO 27001), helping you win bigger clients that require it.', ARRAY['Full ISMS gap analysis','Documentation build-out','Internal audit preparation','Ongoing compliance support through certification']::text[], 'Businesses tendering for contracts that require formal certification.', 'POA', 'ONE_TIME', false, true, true, 3, 'service-governance-risk-compliance', CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "packages" SET "slug" = 'grc-certification-ready', "tier" = 'Pro', "shortDescription" = 'We prepare your business for official certification (e.g. ISO 27001), helping you win bigger clients that require it.', "features" = ARRAY['Full ISMS gap analysis','Documentation build-out','Internal audit preparation','Ongoing compliance support through certification']::text[], "bestFor" = 'Businesses tendering for contracts that require formal certification.', "priceType" = 'POA', "billingType" = 'ONE_TIME', "purchasable" = false, "isPublished" = true, "sortOrder" = 3, "serviceId" = 'service-governance-risk-compliance' WHERE "slug" = 'grc-certification-ready' AND "serviceId" IS NULL;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-new-business-launch', 'bundle-new-business-launch', 'New Business Launch Bundle', 'Website and branding Starter packages to launch your business. Growth alternatives can be agreed during consultation.', false, true, 1, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-new-business-launch', "id", 0 FROM "packages" WHERE "slug" = 'website-get-online' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-new-business-launch', "id", 1 FROM "packages" WHERE "slug" = 'branding-look-professional' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-sme-security-compliance', 'bundle-sme-security-compliance', 'SME Security & Compliance Bundle', 'Practical protection plus the policies and evidence to prove it — ideal before a client audit or insurance renewal.', false, true, 2, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-sme-security-compliance', "id", 0 FROM "packages" WHERE "slug" = 'cybersecurity-stay-protected' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-sme-security-compliance', "id", 1 FROM "packages" WHERE "slug" = 'grc-get-compliant' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-full-digital-foundation', 'bundle-full-digital-foundation', 'Full Digital Foundation', 'A complete, secure digital presence in one package, priced as a bundle.', false, true, 3, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-full-digital-foundation', "id", 0 FROM "packages" WHERE "slug" = 'website-grow-business' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-full-digital-foundation', "id", 1 FROM "packages" WHERE "slug" = 'branding-complete-brand-look' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-full-digital-foundation', "id", 2 FROM "packages" WHERE "slug" = 'cybersecurity-health-check' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-brand-marketing', 'bundle-brand-marketing', 'Brand & Marketing Bundle', 'A consistent identity plus the marketing materials to actually put it to work — ideal ahead of a launch or campaign.', false, true, 4, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-brand-marketing', "id", 0 FROM "packages" WHERE "slug" = 'branding-complete-brand-look' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-brand-marketing', "id", 1 FROM "packages" WHERE "slug" = 'graphic-design-marketing-collateral' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-complete-online-growth', 'bundle-complete-online-growth', 'Complete Online Growth Bundle', 'A professional site, a consistent identity, and the ongoing SEO/content/social engine to actually drive traffic to it — priced as a bundle.', false, true, 5, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-complete-online-growth', "id", 0 FROM "packages" WHERE "slug" = 'website-grow-business' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-complete-online-growth', "id", 1 FROM "packages" WHERE "slug" = 'marketing-grow-your-traffic' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-complete-online-growth', "id", 2 FROM "packages" WHERE "slug" = 'branding-look-professional' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-local-business-visibility', 'bundle-local-business-visibility', 'Local Business Visibility Bundle', 'An affordable entry point for sole traders and local businesses who need a site and to actually be found on Google.', false, true, 6, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-local-business-visibility', "id", 0 FROM "packages" WHERE "slug" = 'website-get-online' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-local-business-visibility', "id", 1 FROM "packages" WHERE "slug" = 'marketing-get-found' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-secure-ai-transformation', 'bundle-secure-ai-transformation', 'Secure AI Transformation Bundle', 'VolTechAI''s flagship package: AI adoption implemented securely from day one, paired with the visibility to attract customers to the newly AI-enabled business.', true, true, 7, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-secure-ai-transformation', "id", 0 FROM "packages" WHERE "slug" = 'ai-powered-automation' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-secure-ai-transformation', "id", 1 FROM "packages" WHERE "slug" = 'cybersecurity-health-check' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-secure-ai-transformation', "id", 2 FROM "packages" WHERE "slug" = 'marketing-get-found' ON CONFLICT DO NOTHING;
INSERT INTO "bundles" ("id", "slug", "name", "shortDescription", "isSignature", "isPublished", "sortOrder", "updatedAt") VALUES ('bundle-bundle-ai-ready-business', 'bundle-ai-ready-business', 'AI-Ready Business Bundle', 'A low-cost entry point for a brand-new SME to launch online, look professional, and start using AI from day one.', true, true, 8, CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-ai-ready-business', "id", 0 FROM "packages" WHERE "slug" = 'ai-readiness-strategy' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-ai-ready-business', "id", 1 FROM "packages" WHERE "slug" = 'website-get-online' ON CONFLICT DO NOTHING;
INSERT INTO "bundle_components" ("bundleId", "packageId", "sortOrder") SELECT 'bundle-bundle-ai-ready-business', "id", 2 FROM "packages" WHERE "slug" = 'branding-look-professional' ON CONFLICT DO NOTHING;
INSERT INTO "service_aliases" ("slug", "serviceId") VALUES ('digital-marketing-seo', 'service-seo') ON CONFLICT DO NOTHING;
INSERT INTO "service_aliases" ("slug", "serviceId") VALUES ('web-services', 'service-website-design-development') ON CONFLICT DO NOTHING;

-- Defense in depth: these rules also apply to direct SQL writes.
ALTER TABLE "packages" ADD CONSTRAINT "package_checkout_rules" CHECK (NOT "purchasable" OR ("priceType" = 'FIXED' AND "billingType" = 'ONE_TIME' AND "amount" IS NOT NULL AND "amount" >= 30 AND "amount" <= 99999999 AND "currency" = 'gbp'));
ALTER TABLE "packages" ADD CONSTRAINT "package_amount_nonnegative" CHECK ("amount" IS NULL OR "amount" >= 0);
COMMIT;
